import type { Metadata } from "next";
import { Playfair_Display, Karla } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${karla.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <div className="mx-[250px] mt-[48px]">
            <NavBar />
          </div>
          <main className="flex-1 mx-[250px] mt-[64px]">{children}</main>
        </div>
      </body>
    </html>
  );
}
